root: true

env:
  browser: true
  node: false

parser: babel-eslint

extends:
  - airbnb

rules:
  no-unused-vars:
    - error
    - args: after-used
      argsIgnorePattern: ^_

  jsx-a11y/label-has-associated-control:
    - error
    - labelComponents:
        - label
      controlComponents:
        - textarea
