version: '3.8'
services:
  server:
    container_name: server
    hostname: server
    build:
      context: .
      dockerfile: server.Dockerfile
    expose:
      - 3000
    restart: always

  client:
    container_name: client
    hostname: client
    build:
      context: .
      dockerfile: client.Dockerfile
    expose:
      - 80
    restart: always
    depends_on:
      - server

networks:
  default:
    external:
      name: nginx-proxy
