version: '3.8'
services:
  server:
    environment:
      CORS_ORIGIN: http://my-chat.localhost
      VIRTUAL_HOST: api.my-chat.localhost
  client:
    build:
      args:
        REST_API_SERVER: http://api.my-chat.localhost
        WEBSOCKET_API_SERVER: ws://api.my-chat.localhost
    environment:
      VIRTUAL_HOST: my-chat.localhost
